spring.application.name=BankIt
spring.datasource.url=jdbc:mysql://localhost:3306/bankit_db
spring.datasource.username=root
spring.datasource.password=Sanjiv@1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username= sanjivkushwaha19012001@gmail.com
spring.mail.password=fqmgpjqkizuqnfxb
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.from=sanjivkushwaha19012001@gmail.com
server.port=8081
#//http://localhost:8081/swagger-ui/index.html.